version: '3.8'

services:
  api:
    build:
      args:
        - API_USER_USERNAME=${API_USER_USERNAME}
        - API_USER_UID=${API_USER_UID}
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    container_name: another_docker_project-api
    restart: unless-stopped
    working_dir: /var/www/

  nginx:
    build:
      context: ./nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"