version: '3.8'

services:
### Nginx ###########################################
  nginx:
    volumes:
      - ${PHP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}/prod:/etc/nginx/sites-available
      - auth-frontend-static-content:/usr/share/nginx/html/auth

### Frontend ###########################################
  frontend:
    build:
      dockerfile: prod.Dockerfile
    volumes:
      - auth-frontend-static-content:/app/auth/dist

volumes:
  auth-frontend-static-content: